Numpy(Numerical Python)
    - Allows faster Mathematical Operations

In [1]:
import numpy as np

List vs Numpy

In [2]:
from time import process_time

p_List = [i for i in range(10000)]
startTime = process_time()
p_List = [i+5 for i in range(10000)]
endTime = process_time()

print(endTime-startTime)

0.015625


In [3]:
npArr = np.array([i for i in range(10000)])
npStartTime = process_time()
npArr += 5
npEndTime = process_time()
print(npEndTime-npStartTime)

0.0


Numpy arrays

In [7]:
list1 =[1,2,34,5]
print(type(list1))

nlist = np.array([1,2,3,4,5])
print(type(nlist))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
nlist.shape

(5,)

In [17]:
ndlist = np.array([(1,2,3,4,5),(3,6,4,5,5)])
ndlist.shape

(2, 5)

In [19]:
arr1 = np.array([(1,2,3,4,5),(3,6,4,5,5)],dtype=float)
print(arr1)

[[1. 2. 3. 4. 5.]
 [3. 6. 4. 5. 5.]]


Initialize placeholders in numpy arrays

In [33]:
arr2 = np.zeros((4,3))
print(arr2)

arr3 = np.ones((4,3))
print(arr3)

#creating an np array in specified value
arr4 = np.full((4,5),5)
print(arr4)


#creating in identity matrix
# i.e: In an Identity matrix both the rows and Columns are equal
arr5 = np.eye(4) 
print(arr5)


# crteate a np array with random values
# i.e: by default th values will be b/w 0-1
arr6 = np.random.random((3,4))
print(arr6)

# random integer value array for specific values
arr7 = np.random.randint(10,69,(3,5))
print(arr7)

# array for evenly spaceed values
arr8 = np.linspace(10,300,5)
print(arr8)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.92478201 0.04763658 0.78222654 0.25160625]
 [0.98170798 0.76792548 0.12265149 0.56215881]
 [0.55460927 0.00845885 0.94623618 0.84280308]]
[[17 21 35 63 42]
 [67 55 18 35 50]
 [13 40 66 31 59]]
[ 10.   82.5 155.  227.5 300. ]


Analyzing a np array

In [37]:
arr10 = np.random.randint(10,69,(3,5))


#find array dimensions
print(arr10.shape)

#find no of dimensions
print(arr10.ndim)

#find no of elements in an array
print(arr10.size)

#checking the datatype
print(arr10.dtype)

(3, 5)
2
15
int32


Mathematical Operations that can be performed in an array

In [44]:
a = np.random.randint(10,69,5)
b = np.random.randint(10,69,5)

print(a)
print(b)

# mathematical operaions on elements of two seperate arrays
print(a+b)
print(a-b)
print(a*b)
print(a/b)

#or 

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[15 27 28 67 27]
[55 68 32 42 58]
[ 70  95  60 109  85]
[-40 -41  -4  25 -31]
[ 825 1836  896 2814 1566]
[0.27272727 0.39705882 0.875      1.5952381  0.46551724]
[ 70  95  60 109  85]
[-40 -41  -4  25 -31]
[ 825 1836  896 2814 1566]
[0.27272727 0.39705882 0.875      1.5952381  0.46551724]


Array manipulation

In [48]:
array = np.random.randint(0,10,(2,10))
print(array)

#find transpose of a matrix
trans = np.transpose(array)
print(trans)

#or 

trans2 = array.T
print(trans2)

[[9 5 0 6 1 4 2 4 4 1]
 [0 0 6 1 4 1 1 1 8 4]]
[[9 0]
 [5 0]
 [0 6]
 [6 1]
 [1 4]
 [4 1]
 [2 1]
 [4 1]
 [4 8]
 [1 4]]
[[9 0]
 [5 0]
 [0 6]
 [6 1]
 [1 4]
 [4 1]
 [2 1]
 [4 1]
 [4 8]
 [1 4]]


Reshaping a array

In [50]:
b = trans2.reshape(10,2)
print(b)

[[9 0]
 [5 0]
 [0 6]
 [6 1]
 [1 4]
 [4 1]
 [2 1]
 [4 1]
 [4 8]
 [1 4]]
